# Jekyll Defaults
title: Hello World
description: Still getting aqainted with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: "cubesnail.me"
github: http://github.com/cubesnail

markdown: redcarpet
highlighter: rouge
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
