# Jekyll Defaults
title: Little Big Blue
email: your-email@domain.com
description: A small and simple site I made to test out Jekyll. Watch out! I'm going to make a material design theme next!
baseurl: "" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "http://localhost:3000"
github: http://github.com/ITSJOHNCENA
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites

markdown: redcarpet
highlighter: rouge
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
